version: "1.0"
services:
  app:
    image: harshit831898/tracker1:10
    ports:
      - 80:8000
    depends_on:
      - mysql
    networks:
      - net-1

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: freedb_Tracker
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - vol-1:/var/lib/mysql
    networks:
      - net-1
volumes:
  vol-1:
networks:
 net-1:
   driver: bridge
    
