version: "1.7"
services:
  app:
    image: harshit831898/tracker1:36
    ports:
      - 80:8000
    depends_on:
      - mysql
    networks:
      - net-1

  mysql:
    build: ./mysql/
    restart: always
    environment:
      - MYSQL_DATABASE=freedb_Tracker
      - MYSQL_USER=Harshit
      - MYSQL_PASSWORD=Harshit
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks:
      - net-1
    volumes:
      - vol-1:/var/lib/mysql
networks:
  net-1:
    driver: bridge
volumes:
  vol-1:
    driver: local
    
